"""Initial schema — projects, templates, notifications, deliveries, outbox.

Revision ID: 0001
Revises:
Create Date: 2026-08-27

Written by hand rather than autogenerated, because autogenerate produces
CREATE TYPE statements it then also emits inside create_table, and the second
one fails. The enum types are created once here with create_type=False on every
column that uses them.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# create_type=False everywhere: the types are created explicitly in upgrade(),
# and letting a column definition create them too is a duplicate-object error.
channel = postgresql.ENUM(
    "email", "sms", "push", "inapp", "sse", name="channel", create_type=False
)
notification_status = postgresql.ENUM(
    "accepted", "fanned_out", "completed", "failed", name="notification_status", create_type=False
)
delivery_status = postgresql.ENUM(
    "pending",
    "sending",
    "sent",
    "retrying",
    "failed",
    "dead",
    name="delivery_status",
    create_type=False,
)
recipient_type = postgresql.ENUM("kc_sub", name="recipient_type", create_type=False)


def upgrade() -> None:
    bind = op.get_bind()

    channel.create(bind, checkfirst=True)
    notification_status.create(bind, checkfirst=True)
    delivery_status.create(bind, checkfirst=True)
    recipient_type.create(bind, checkfirst=True)

    # -- projects -----------------------------------------------------------
    op.create_table(
        "projects",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("client_id", sa.String(length=255), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("key ~ '^[a-z0-9][a-z0-9_-]*$'", name="ck_projects_key_slug"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
        sa.UniqueConstraint("client_id"),
    )
    op.create_index("ix_projects_client_id", "projects", ["client_id"])
    op.create_index("ix_projects_created_at", "projects", ["created_at"])

    # -- templates ----------------------------------------------------------
    op.create_table(
        "templates",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("channel", channel, nullable=False),
        sa.Column("locale", sa.String(length=16), server_default="en", nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.CheckConstraint(
            "channel <> 'email' OR subject IS NOT NULL", name="ck_templates_email_has_subject"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "key", "channel", "locale", "version", name="uq_templates_identity"
        ),
    )
    op.create_index("ix_templates_created_at", "templates", ["created_at"])
    op.create_index(
        "ix_templates_active_lookup",
        "templates",
        ["project_id", "key", "channel", "locale"],
        postgresql_where=sa.text("active"),
    )

    # -- notifications ------------------------------------------------------
    op.create_table(
        "notifications",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("recipient_type", recipient_type, nullable=False),
        sa.Column("recipient_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("template_key", sa.String(length=128), nullable=False),
        sa.Column("locale", sa.String(length=16), server_default="en", nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}",
            nullable=False,
        ),
        sa.Column("channels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", notification_status, server_default="accepted", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.CheckConstraint(
            "jsonb_typeof(channels) = 'array'", name="ck_notifications_channels_array",
        ),
        sa.CheckConstraint(
            "jsonb_array_length(channels) > 0", name="ck_notifications_channels_nonempty"
        ),
        sa.PrimaryKeyConstraint("id"),
        # The idempotency guarantee, in one line. Not to be cut.
        sa.UniqueConstraint("project_id", "idempotency_key", name="uq_notifications_idempotency"),
    )
    op.create_index("ix_notifications_created_at", "notifications", ["created_at"])
    op.create_index(
        "ix_notifications_project_created", "notifications", ["project_id", "created_at"],
    )
    op.create_index("ix_notifications_recipient", "notifications", ["project_id", "recipient_id"])

    # -- deliveries ---------------------------------------------------------
    op.create_table(
        "deliveries",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("notification_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("channel", channel, nullable=False),
        sa.Column("status", delivery_status, server_default="pending", nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("template_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("provider_message_id", sa.String(length=255), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["notification_id"], ["notifications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["template_id"], ["templates.id"], ondelete="SET NULL"),
        sa.CheckConstraint("attempts >= 0", name="ck_deliveries_attempts_nonnegative"),
        sa.PrimaryKeyConstraint("id"),
        # Makes a second fan-out for the same message a no-op rather than a
        # duplicate email. Fan-out is at-least-once, so this will be exercised.
        sa.UniqueConstraint(
            "notification_id", "channel", name="uq_deliveries_notification_channel",
        ),
    )
    op.create_index("ix_deliveries_created_at", "deliveries", ["created_at"])
    op.create_index("ix_deliveries_status_due", "deliveries", ["status", "next_attempt_at"])
    op.create_index("ix_deliveries_project_created", "deliveries", ["project_id", "created_at"])

    # -- outbox -------------------------------------------------------------
    op.create_table(
        "outbox",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("event_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("notification_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("topic", sa.String(length=128), nullable=False),
        sa.Column("partition_key", sa.String(length=255), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["notification_id"], ["notifications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id"),
    )
    op.create_index("ix_outbox_created_at", "outbox", ["created_at"])
    # Partial. The dispatcher only ever reads the unpublished rows, and a full
    # index would grow with the published ones forever.
    op.create_index(
        "ix_outbox_unpublished", "outbox", ["id"], postgresql_where=sa.text("published_at IS NULL")
    )


def downgrade() -> None:
    op.drop_table("outbox")
    op.drop_table("deliveries")
    op.drop_table("notifications")
    op.drop_table("templates")
    op.drop_table("projects")

    bind = op.get_bind()
    recipient_type.drop(bind, checkfirst=True)
    delivery_status.drop(bind, checkfirst=True)
    notification_status.drop(bind, checkfirst=True)
    channel.drop(bind, checkfirst=True)
