version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "pip"
    directory: "/backend/ml"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "pip"
    directory: "/backend/auth"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "pip"
    directory: "/backend/notify"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/frontend/keycloak-theme"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
