/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Process liveness */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness, including dependencies */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register or refresh this device's push token (idempotent on token)
         * @description Call on sign-in and on every token refresh. Re-binds a token to the caller.
         */
        post: operations["register_device_v1_me_devices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/devices/unregister": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop push to this device (call on sign-out; idempotent)
         * @description Deactivates the caller's own row for this token; 204 whether or not one existed.
         */
        post: operations["unregister_device_v1_me_devices_unregister_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's notifications, newest first */
        get: operations["list_my_notifications_v1_me_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark one of the caller's notifications read (idempotent)
         * @description Another user's notification is a 404, never a 403, so ids cannot be probed.
         */
        post: operations["mark_read_v1_me_notifications__notification_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a notification for delivery
         * @description Accept a notification and return 202 without delivering anything.
         *
         *     202 rather than 201: the notification is accepted, and delivery has not
         *     happened yet and may still fail. Returning 201 would claim a resource whose
         *     observable effect — an email arriving — does not exist yet.
         */
        post: operations["create_notification_v1_notifications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications/{notification_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read back one notification belonging to the calling project
         * @description Read one notification.
         *
         *     The project_id predicate is not an optimisation. Another project's
         *     notification returns 404 and not 403, so this cannot be used to discover
         *     which ids exist elsewhere.
         */
        get: operations["get_notification_v1_notifications__notification_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications/{notification_id}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What happened to each channel's copy of one notification
         * @description The diagnostic surface: did it arrive, and if not, why not.
         *
         *     v0.1 has no admin console, so this endpoint plus the worker's logs is how a
         *     delivery is investigated. `attempts` and `last_error` are the two fields that
         *     answer the question in practice — a status of `retrying` on attempt 3 with a
         *     `next_attempt_at` four minutes out is a complete account of where a message
         *     is and what is wrong with it.
         */
        get: operations["list_deliveries_v1_notifications__notification_id__deliveries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List this project's templates */
        get: operations["list_templates_v1_templates_get"];
        put?: never;
        /**
         * Store a new version of a template
         * @description Write the next version of one template and make it the active one.
         *
         *     201 rather than 200: a version is created every time, even when the text is
         *     unchanged. Returning 200 would suggest an in-place edit, which is exactly
         *     what this does not do.
         */
        post: operations["create_template_v1_templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one template belonging to the calling project */
        get: operations["get_template_v1_templates__template_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DeliveryList */
        DeliveryList: {
            /** Deliveries */
            deliveries: components["schemas"]["DeliveryResponse"][];
            /**
             * Notification Id
             * Format: uuid
             */
            notification_id: string;
            status: components["schemas"]["NotificationStatus"];
        };
        /**
         * DeliveryResponse
         * @description What actually happened to one channel's copy of a notification.
         *
         *     This is the diagnostic surface for v0.1: there is no admin console, so the
         *     answer to "did it arrive, and if not why not" is this endpoint plus the
         *     worker's delivery logs.
         */
        DeliveryResponse: {
            /** Address */
            address: string | null;
            /** Attempts */
            attempts: number;
            /** Channel */
            channel: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Device Id */
            device_id?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Error */
            last_error: string | null;
            /** Next Attempt At */
            next_attempt_at: string | null;
            /** Provider Message Id */
            provider_message_id: string | null;
            /** Sent At */
            sent_at: string | null;
            status: components["schemas"]["DeliveryStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * DeliveryStatus
         * @enum {string}
         */
        DeliveryStatus: "pending" | "sending" | "sent" | "retrying" | "failed" | "dead";
        /**
         * DeviceRegister
         * @description Register or refresh this install's native push token. Idempotent on token.
         * @example {
         *       "apns_environment": "sandbox",
         *       "app_version": "1.0.0 (42)",
         *       "platform": "ios",
         *       "token": "a1b2c3d4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5c6d7e8f90"
         *     }
         */
        DeviceRegister: {
            /** Apns Environment */
            apns_environment?: ("sandbox" | "production") | null;
            /** App Version */
            app_version?: string | null;
            /**
             * Platform
             * @enum {string}
             */
            platform: "android" | "ios";
            /** Token */
            token: string;
        };
        /** DeviceResponse */
        DeviceResponse: {
            /** Active */
            active: boolean;
            /** Apns Environment */
            apns_environment: string | null;
            /** App Version */
            app_version: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
            /** Platform */
            platform: string;
        };
        /** DeviceUnregister */
        DeviceUnregister: {
            /** Token */
            token: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
            /** Error */
            error: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InboxItem
         * @description One notification addressed to the caller. A routing hint plus display text.
         */
        InboxItem: {
            /** Body */
            body: string | null;
            /** Case Ref */
            case_ref: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Data */
            data?: {
                [key: string]: string;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Project */
            project: string;
            /** Read */
            read: boolean;
            /** Read At */
            read_at: string | null;
            /** Title */
            title: string | null;
            /** Type */
            type: string;
        };
        /** InboxPage */
        InboxPage: {
            /** Items */
            items: components["schemas"]["InboxItem"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Unread Count */
            unread_count: number;
        };
        /**
         * NotificationAccepted
         * @description The 202 body.
         *
         *     A replayed idempotency key returns this same body, byte for byte, including
         *     the original created_at. A caller that retries cannot tell the difference,
         *     which is the whole point — it can retry freely.
         */
        NotificationAccepted: {
            /** Channels */
            channels: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Idempotency Key */
            idempotency_key: string;
            recipient: components["schemas"]["Recipient"];
            status: components["schemas"]["NotificationStatus"];
        };
        /**
         * NotificationCreate
         * @example {
         *       "channels": [
         *         "email"
         *       ],
         *       "idempotency_key": "swagger-demo-0001",
         *       "locale": "en",
         *       "payload": {
         *         "first_name": "Ada"
         *       },
         *       "recipient": {
         *         "id": "6f1b3c7e-2f4a-4f1e-9c3d-5a7b8e9f0a1b",
         *         "type": "kc_sub"
         *       },
         *       "template_key": "welcome"
         *     }
         */
        NotificationCreate: {
            /**
             * Channels
             * @description Where to deliver. One or several — the caller chooses, and there is no default: a call that does not say where a message should go is not finished. Deliverable in this release: email, inapp, push.
             */
            channels: string[];
            /**
             * Idempotency Key
             * @description Unique within the project. Use a natural key where one exists — an invoice id, a leave-request id. Submitting the same key twice returns the first notification unchanged instead of creating a second.
             */
            idempotency_key: string;
            /**
             * Locale
             * @description Template locale to render in.
             * @default en
             */
            locale: string;
            /**
             * Payload
             * @description Values substituted into the template when it is rendered.
             */
            payload?: {
                [key: string]: unknown;
            };
            recipient: components["schemas"]["Recipient"];
            /**
             * Template Key
             * @description Which stored template renders this message.
             */
            template_key: string;
        };
        /**
         * NotificationStatus
         * @enum {string}
         */
        NotificationStatus: "accepted" | "fanned_out" | "completed" | "failed";
        /**
         * Recipient
         * @description Who the notification is for. The closed identifier space, AD-8.
         *
         *     'kc_sub' is the Keycloak subject: the stable, opaque user id from the token.
         *     Not an email address, not an employee number, not a phone number. Those are
         *     application-owned identifier spaces, and accepting more than one of them
         *     produces silent empty-result defects that nothing reports.
         */
        Recipient: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Type
             * @constant
             */
            type: "kc_sub";
        };
        /**
         * TemplateCreate
         * @description A new template version for the calling project.
         *
         *     There is no update. Posting the same key, channel and locale again creates
         *     the next version and deactivates the previous one, because a delivery records
         *     which template produced it and editing a row in place would rewrite the
         *     history of what has already been sent.
         * @example {
         *       "body": "Hello {{ first_name }},\n\nYour account is ready.\n\n— ADA\n",
         *       "channel": "email",
         *       "key": "welcome",
         *       "locale": "en",
         *       "subject": "Welcome to ADA, {{ first_name }}"
         *     }
         */
        TemplateCreate: {
            /** Body */
            body: string;
            /**
             * Channel
             * @description Deliverable in this release: email, inapp, push
             */
            channel: string;
            /** Key */
            key: string;
            /**
             * Locale
             * @default en
             */
            locale: string;
            /** Subject */
            subject?: string | null;
        };
        /** TemplateResponse */
        TemplateResponse: {
            /** Active */
            active: boolean;
            /** Body */
            body: string;
            /** Channel */
            channel: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key */
            key: string;
            /** Locale */
            locale: string;
            /** Subject */
            subject: string | null;
            /** Version */
            version: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    register_device_v1_me_devices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceRegister"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"];
                };
            };
            /** @description No token, or the token is not acceptable */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not an end-user token from an allowed client */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unregister_device_v1_me_devices_unregister_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceUnregister"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No token, or the token is not acceptable */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not an end-user token from an allowed client */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_notifications_v1_me_notifications_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
                /** @description Render title/body in this locale, e.g. 'hi' */
                locale?: string | null;
                /** @description Filter by project key, e.g. 'ada' */
                project?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxPage"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No token, or the token is not acceptable */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not an end-user token from an allowed client */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_read_v1_me_notifications__notification_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No token, or the token is not acceptable */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not an end-user token from an allowed client */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_notification_v1_notifications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationAccepted"];
                };
            };
            /** @description No token, or the token is not acceptable */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Valid token, but not for a live project */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The body does not satisfy the contract */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_notification_v1_notifications__notification_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationAccepted"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_deliveries_v1_notifications__notification_id__deliveries_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryList"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_v1_templates_get: {
        parameters: {
            query?: {
                /** @description Include superseded versions, not only the active ones. */
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_template_v1_templates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The body does not satisfy the contract */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_template_v1_templates__template_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
