from __future__ import annotations

from datetime import date
from typing import Literal

from ada_core.datetimes import IstDateTime, now_ist
from ada_core.models_icms import CASE_PRIORITIES
from ada_core.validation import (
    ULPIN,
    Code,
    Email,
    IdempotencyKey,
    KhasraNo,
    Latitude,
    LGDCode,
    Longitude,
    Name,
    PhoneIN,
    PinCode,
    PlaceName,
    SafeLongText,
    SafeText,
)
from fastapi import UploadFile
from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    computed_field,
    field_validator,
    model_validator,
)

from .collection import CollectionParams
from .schemas import UserId, ZoneCode
from .workflow import Status

__all__ = [
    "CaseAmend",
    "CaseAssign",
    "CaseAssignmentOut",
    "CaseClose",
    "CaseConfirm",
    "CaseCreate",
    "CaseDetail",
    "CaseEvidenceCreate",
    "CaseEvidenceList",
    "CaseEvidenceOut",
    "CaseEvidenceWritten",
    "CaseHandover",
    "CaseQuery",
    "CaseReject",
    "CaseRow",
    "InspectionRoundOut",
]

SOURCES = ("detection", "public", "field", "office")
STATUSES = tuple(str(s) for s in Status)
PRIORITIES = CASE_PRIORITIES
EARLIEST_COMPLAINT_DATE = date(2000, 1, 1)

# The codes ada-core 0022 seeds into icms_code_value (case_reject_reason, case_close_outcome).
REJECT_REASONS = ("false_complaint", "duplicate", "outside_jurisdiction",
                  "no_violation_found", "other")
CLOSE_OUTCOMES = ("demolished_by_owner", "demolished_by_authority", "regularised",
                  "court_case_filed", "sealed", "other")
OTHER_REMARKS_MIN = 10


def today_ist() -> date:
    return now_ist().date()


class CaseLocation(BaseModel):
    model_config = ConfigDict(extra="forbid")

    latitude: Latitude
    longitude: Longitude


class CaseCreate(BaseModel):
    model_config = ConfigDict(extra="forbid")

    source: str = Field(description=f"One of: {', '.join(SOURCES)}")
    zone_cd: ZoneCode | None = None
    location: CaseLocation | None = None

    detection_id: int | None = Field(
        default=None,
        description="The change polygon this case came from, when source is 'detection'.",
    )

    complaint_type_cd: Code | None = None
    other_type: SafeText | None = None
    detail: SafeLongText | None = None

    complainant_name: Name | None = None
    complainant_phone: PhoneIN | None = None
    complainant_email: Email | None = None

    owner_name: Name | None = None
    owner_phone: PhoneIN | None = None

    property_address: SafeText | None = None
    landmark: PlaceName | None = None
    police_station: PlaceName | None = None
    pin_code: PinCode | None = None
    district: PlaceName | None = None
    state: PlaceName | None = None
    country: PlaceName | None = "India"
    property_type_cd: Code | None = None
    floor_count: int | None = Field(default=None, ge=0, le=200)

    ulpin: ULPIN | None = Field(default=None, description="Bhu-Aadhaar, 14 characters.")
    khasra_no: KhasraNo | None = None
    village_lgd_code: LGDCode | None = None
    district_lgd_code: LGDCode | None = None
    priority: Literal[PRIORITIES] | None = None  # type: ignore[valid-type]
    complaint_date: date | None = Field(
        default=None,
        description="The date the complaint was made, IST. Not in the future and not "
                    "before 2000-01-01. Omitted, it is today.",
    )

    idempotency_key: IdempotencyKey | None = Field(
        default=None,
        description="Generated by the client at user-action time, not at send time. "
                    "A replay returns the case the first attempt created rather than "
                    "filing the complaint twice.",
    )

    @field_validator("complaint_date")
    @classmethod
    def _a_plausible_complaint_date(cls, value: date | None) -> date | None:
        if value is None:
            return value
        if value > today_ist():
            raise ValueError("complaint_date cannot be in the future")
        if value < EARLIEST_COMPLAINT_DATE:
            raise ValueError("complaint_date cannot be before 2000-01-01")
        return value

    @model_validator(mode="after")
    def _locatable_and_coherent(self) -> CaseCreate:
        if self.source not in SOURCES:
            raise ValueError(f"source must be one of: {', '.join(SOURCES)}")
        if self.zone_cd is None and self.location is None:
            raise ValueError(
                "give either zone_cd or location; the zone is resolved from the "
                "location when one is supplied"
            )
        if self.source == "detection" and self.detection_id is None:
            raise ValueError("source 'detection' requires detection_id")
        if self.source != "detection" and self.detection_id is not None:
            raise ValueError("detection_id is only meaningful when source is 'detection'")
        if self.complaint_type_cd == "other" and not self.other_type:
            raise ValueError("complaint_type_cd 'other' requires other_type")
        return self


class CaseAmend(BaseModel):
    model_config = ConfigDict(extra="forbid")

    complaint_type_cd: Code | None = None
    other_type: SafeText | None = None
    detail: SafeLongText | None = None

    complainant_name: Name | None = None
    complainant_phone: PhoneIN | None = None
    complainant_email: Email | None = None

    owner_name: Name | None = None
    owner_phone: PhoneIN | None = None

    property_address: SafeText | None = None
    landmark: PlaceName | None = None
    police_station: PlaceName | None = None
    pin_code: PinCode | None = None
    district: PlaceName | None = None
    state: PlaceName | None = None
    country: PlaceName | None = None
    property_type_cd: Code | None = None
    floor_count: int | None = Field(default=None, ge=0, le=200)

    ulpin: ULPIN | None = None
    khasra_no: KhasraNo | None = None
    village_lgd_code: LGDCode | None = None
    district_lgd_code: LGDCode | None = None
    priority: Literal[PRIORITIES] | None = None  # type: ignore[valid-type]

    @model_validator(mode="after")
    def _not_empty(self) -> CaseAmend:
        if not self.model_fields_set:
            raise ValueError("send at least one field to amend")
        return self

    def changes(self) -> dict:
        return self.model_dump(exclude_unset=True)


class CaseAssign(BaseModel):
    model_config = ConfigDict(extra="forbid")

    assignee_user_id: UserId
    note: SafeText | None = None
    reason: SafeText | None = None


# Stages 6 and 7 carry no `requires`, so the note is the whole of the body.
class CaseHandover(BaseModel):
    model_config = ConfigDict(extra="forbid")

    note: SafeText | None = Field(
        default=None,
        description="Why the case is being handed over, recorded on the event row.",
    )


class CaseConfirm(BaseModel):
    model_config = ConfigDict(extra="forbid")

    note: SafeText | None = Field(
        default=None,
        description="The Project Lead's remark, recorded on the event row.",
    )


def _remarks_for_other(code: str, remarks: str | None) -> None:
    if code == "other" and len((remarks or "").strip()) < OTHER_REMARKS_MIN:
        raise ValueError(
            f"remarks of at least {OTHER_REMARKS_MIN} characters are required when the "
            "reason is other")


class CaseReject(BaseModel):
    model_config = ConfigDict(extra="forbid")

    reason_cd: Literal[REJECT_REASONS] = Field(  # type: ignore[valid-type]
        description="A `case_reject_reason` code.")
    remarks: SafeLongText | None = Field(
        default=None, description=f"Required, {OTHER_REMARKS_MIN}+ characters, when "
                                  "`reason_cd` is `other`.")
    idempotency_key: IdempotencyKey | None = Field(
        default=None, description="A replay with the same key returns the case unchanged.")

    @model_validator(mode="after")
    def _other_needs_remarks(self) -> CaseReject:
        _remarks_for_other(self.reason_cd, self.remarks)
        return self


class CaseClose(BaseModel):
    model_config = ConfigDict(extra="forbid")

    outcome_cd: Literal[CLOSE_OUTCOMES] = Field(  # type: ignore[valid-type]
        description="A `case_close_outcome` code.")
    remarks: SafeLongText | None = Field(
        default=None, description=f"Required, {OTHER_REMARKS_MIN}+ characters, when "
                                  "`outcome_cd` is `other`.")
    idempotency_key: IdempotencyKey | None = Field(
        default=None, description="A replay with the same key returns the case unchanged.")

    @model_validator(mode="after")
    def _other_needs_remarks(self) -> CaseClose:
        _remarks_for_other(self.outcome_cd, self.remarks)
        return self


class CaseQuery(CollectionParams):
    status: list[str] | None = Field(
        default=None, description=f"Repeatable. One of: {', '.join(STATUSES)}")
    stage_no: list[int] | None = Field(default=None, description="Repeatable, 1-7.")
    zone_cd: list[ZoneCode] | None = Field(default=None, description="Repeatable.")
    complaint_type_cd: list[Code] | None = Field(default=None, description="Repeatable.")
    source: list[str] | None = Field(default=None, description="Repeatable.")
    assignee_user_id: list[UserId] | None = Field(
        default=None, description="Repeatable. Matches the OPEN survey assignment only.")
    priority: list[str] | None = Field(
        default=None, description=f"Repeatable. One of: {', '.join(PRIORITIES)}")
    ulpin: list[str] | None = Field(default=None, description="Repeatable. Exact match.")
    khasra_no: list[str] | None = Field(default=None, description="Repeatable. Exact match.")
    village_lgd_code: list[str] | None = Field(default=None, description="Repeatable.")
    mine: bool = Field(
        default=False,
        description="Only cases whose open survey assignment is the caller's. "
                    "This is what the field app sends.",
    )
    filed_from: date | None = Field(default=None, description="Inclusive, on the filed date.")
    filed_to: date | None = Field(default=None, description="Inclusive, on the filed date.")

    @model_validator(mode="after")
    def _known_vocabulary(self) -> CaseQuery:
        for value in self.status or ():
            if value not in STATUSES:
                raise ValueError(f"unknown status '{value}'; one of: {', '.join(STATUSES)}")
        for value in self.source or ():
            if value not in SOURCES:
                raise ValueError(f"unknown source '{value}'; one of: {', '.join(SOURCES)}")
        for value in self.priority or ():
            if value not in PRIORITIES:
                raise ValueError(
                    f"unknown priority '{value}'; one of: {', '.join(PRIORITIES)}")
        for value in self.stage_no or ():
            if not 1 <= value <= 7:
                raise ValueError("stage_no is between 1 and 7")
        if self.filed_from and self.filed_to and self.filed_from > self.filed_to:
            raise ValueError("filed_from must not be after filed_to")
        return self


class CaseRow(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    case_ref: str
    zone_cd: str
    zone_name: str
    property_address: str | None = None
    landmark: str | None = None
    complainant_name: str | None = None
    complaint_type_cd: str | None = None
    complaint_type_label: str | None = None
    other_type: str | None = None
    measured_area_sqm: float | None = None
    priority: str | None = None
    ulpin: str | None = None
    khasra_no: str | None = None
    village_lgd_code: str | None = None
    status: str
    stage_no: int
    current_round: int
    source: str
    assignee_user_id: str | None = None
    raised_at: IstDateTime
    complaint_date: date | None = None

    @computed_field
    @property
    def parcel_id(self) -> str | None:
        if self.ulpin:
            return self.ulpin
        if self.khasra_no:
            return (f"{self.village_lgd_code}/{self.khasra_no}"
                    if self.village_lgd_code else self.khasra_no)
        return None


class CaseAssignmentOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    assignee_user_id: str
    assignee_name: str | None = Field(
        default=None, description="From Keycloak at read time; null when it cannot say.")
    assigned_by: str
    assigned_by_name: str | None = Field(
        default=None, description="From Keycloak at read time; null when it cannot say.")
    assignment_type: str
    note: str | None = None
    assigned_at: IstDateTime
    active: bool
    released_at: IstDateTime | None = None


class InspectionRoundOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    inspection_ref: str
    round_no: int
    surveyor_user_id: str
    surveyor_name: str | None = Field(
        default=None, description="From Keycloak at read time; null when it cannot say.")
    status: str
    submitted_at: IstDateTime | None = None
    measured_area_sqm: float | None = None
    occupant_name: str | None = Field(
        default=None, description="Owner or occupant, as the surveyor recorded on site.")
    occupant_phone: str | None = None
    property_type_cd: str | None = None
    floor_count: int | None = None
    police_station: str | None = None


class CaseDetail(CaseRow):
    detail: str | None = None
    complainant_phone: str | None = None
    complainant_email: str | None = None
    owner_name: str | None = None
    owner_phone: str | None = None
    police_station: str | None = None
    pin_code: str | None = None
    district: str | None = None
    state: str | None = None
    country: str | None = None
    property_type_cd: str | None = None
    floor_count: int | None = None
    detection_id: int | None = None
    district_lgd_code: str | None = None
    idempotency_key: str | None = None
    location: dict | None = None
    closed_at: IstDateTime | None = None
    closed_by: str | None = None
    closed_by_name: str | None = Field(
        default=None, description="From Keycloak at read time; null when it cannot say.")
    outcome_cd: str | None = Field(
        default=None, description="Why it was rejected (`case_reject_reason`) or how it "
                                  "was closed (`case_close_outcome`); null while open.")
    outcome_label: str | None = None
    outcome_label_hi: str | None = None
    outcome_reason: str | None = Field(
        default=None, description="The officer's remarks on the rejection or closure.")
    created_by: str | None = None
    created_by_name: str | None = Field(
        default=None, description="From Keycloak at read time; null when it cannot say.")
    updated_at: IstDateTime

    assignment: CaseAssignmentOut | None = None
    rounds: list[InspectionRoundOut] = Field(default_factory=list)
    evidence_count: int = 0
    allowed_actions: list[str] = Field(
        default_factory=list,
        description="What THIS caller may do next, from workflow.allowed_actions. "
                    "A convenience for rendering buttons, never a control: "
                    "workflow.check runs on every request regardless.",
    )


class CaseEvidenceCreate(BaseModel):
    """The whole multipart body of a case evidence upload, the file included."""

    model_config = ConfigDict(extra="forbid")

    file: UploadFile = Field(description="The photograph: JPEG, PNG or WebP.")
    caption: SafeText | None = None
    latitude: Latitude | None = None
    longitude: Longitude | None = None

    @model_validator(mode="after")
    def _a_position_is_both_halves(self) -> CaseEvidenceCreate:
        if (self.latitude is None) != (self.longitude is None):
            raise ValueError("send both latitude and longitude, or neither")
        return self


class CaseEvidenceOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    filename: str | None = None
    content_type: str | None = None
    size_bytes: int | None = None
    caption: str | None = None
    latitude: float | None = None
    longitude: float | None = None
    created_at: IstDateTime
    content_url: str


class CaseEvidenceWritten(BaseModel):
    evidence: CaseEvidenceOut
    replayed: bool


class CaseEvidenceList(BaseModel):
    items: list[CaseEvidenceOut]


class AssigneeRole(BaseModel):
    role_cd: str
    label: str
    label_hi: str | None = None


class AssigneeCandidate(BaseModel):
    user_id: str
    name: str | None
    username: str | None
    role_cds: list[str]


# The assign dialog's two pickers: roles the workflow admits, then who holds them here.
class AssigneeOptions(BaseModel):
    roles: list[AssigneeRole]
    candidates: list[AssigneeCandidate]
