from __future__ import annotations

from datetime import date
from typing import Literal

from ada_core.datetimes import IstDateTime
from ada_core.models_icms import CASE_PRIORITIES
from ada_core.validation import (
    ULPIN,
    Code,
    Email,
    IdempotencyKey,
    KhasraNo,
    Latitude,
    LGDCode,
    Longitude,
    Name,
    PhoneIN,
    PinCode,
    PlaceName,
    SafeLongText,
    SafeText,
)
from pydantic import BaseModel, ConfigDict, Field, computed_field, model_validator

from .collection import CollectionParams
from .schemas import UserId, ZoneCode
from .workflow import Status

__all__ = [
    "CaseAmend",
    "CaseAssign",
    "CaseAssignmentOut",
    "CaseConfirm",
    "CaseCreate",
    "CaseDetail",
    "CaseHandover",
    "CaseQuery",
    "CaseRow",
    "InspectionRoundOut",
]

SOURCES = ("detection", "public", "field", "office")
STATUSES = tuple(str(s) for s in Status)
PRIORITIES = CASE_PRIORITIES


class CaseLocation(BaseModel):
    model_config = ConfigDict(extra="forbid")

    latitude: Latitude
    longitude: Longitude


class CaseCreate(BaseModel):
    model_config = ConfigDict(extra="forbid")

    source: str = Field(description=f"One of: {', '.join(SOURCES)}")
    zone_cd: ZoneCode | None = None
    location: CaseLocation | None = None

    detection_id: int | None = Field(
        default=None,
        description="The change polygon this case came from, when source is 'detection'.",
    )

    complaint_type_cd: Code | None = None
    other_type: SafeText | None = None
    detail: SafeLongText | None = None

    complainant_name: Name | None = None
    complainant_phone: PhoneIN | None = None
    complainant_email: Email | None = None

    owner_name: Name | None = None
    owner_phone: PhoneIN | None = None

    property_address: SafeText | None = None
    landmark: PlaceName | None = None
    police_station: PlaceName | None = None
    pin_code: PinCode | None = None
    district: PlaceName | None = None
    state: PlaceName | None = None
    country: PlaceName | None = "India"
    property_type_cd: Code | None = None
    floor_count: int | None = Field(default=None, ge=0, le=200)

    ulpin: ULPIN | None = Field(default=None, description="Bhu-Aadhaar, 14 characters.")
    khasra_no: KhasraNo | None = None
    village_lgd_code: LGDCode | None = None
    district_lgd_code: LGDCode | None = None
    priority: Literal[PRIORITIES] | None = None  # type: ignore[valid-type]

    idempotency_key: IdempotencyKey | None = Field(
        default=None,
        description="Generated by the client at user-action time, not at send time. "
                    "A replay returns the case the first attempt created rather than "
                    "filing the complaint twice.",
    )

    @model_validator(mode="after")
    def _locatable_and_coherent(self) -> CaseCreate:
        if self.source not in SOURCES:
            raise ValueError(f"source must be one of: {', '.join(SOURCES)}")
        if self.zone_cd is None and self.location is None:
            raise ValueError(
                "give either zone_cd or location; the zone is resolved from the "
                "location when one is supplied"
            )
        if self.source == "detection" and self.detection_id is None:
            raise ValueError("source 'detection' requires detection_id")
        if self.source != "detection" and self.detection_id is not None:
            raise ValueError("detection_id is only meaningful when source is 'detection'")
        if self.complaint_type_cd == "other" and not self.other_type:
            raise ValueError("complaint_type_cd 'other' requires other_type")
        return self


class CaseAmend(BaseModel):
    model_config = ConfigDict(extra="forbid")

    complaint_type_cd: Code | None = None
    other_type: SafeText | None = None
    detail: SafeLongText | None = None

    complainant_name: Name | None = None
    complainant_phone: PhoneIN | None = None
    complainant_email: Email | None = None

    owner_name: Name | None = None
    owner_phone: PhoneIN | None = None

    property_address: SafeText | None = None
    landmark: PlaceName | None = None
    police_station: PlaceName | None = None
    pin_code: PinCode | None = None
    district: PlaceName | None = None
    state: PlaceName | None = None
    country: PlaceName | None = None
    property_type_cd: Code | None = None
    floor_count: int | None = Field(default=None, ge=0, le=200)

    ulpin: ULPIN | None = None
    khasra_no: KhasraNo | None = None
    village_lgd_code: LGDCode | None = None
    district_lgd_code: LGDCode | None = None
    priority: Literal[PRIORITIES] | None = None  # type: ignore[valid-type]

    @model_validator(mode="after")
    def _not_empty(self) -> CaseAmend:
        if not self.model_fields_set:
            raise ValueError("send at least one field to amend")
        return self

    def changes(self) -> dict:
        return self.model_dump(exclude_unset=True)


class CaseAssign(BaseModel):
    model_config = ConfigDict(extra="forbid")

    assignee_user_id: UserId
    note: SafeText | None = None
    reason: SafeText | None = None


# Stages 6 and 7 carry no `requires`, so the note is the whole of the body.
class CaseHandover(BaseModel):
    model_config = ConfigDict(extra="forbid")

    note: SafeText | None = Field(
        default=None,
        description="Why the case is being handed over, recorded on the event row.",
    )


class CaseConfirm(BaseModel):
    model_config = ConfigDict(extra="forbid")

    note: SafeText | None = Field(
        default=None,
        description="The Project Lead's remark, recorded on the event row.",
    )


class CaseQuery(CollectionParams):
    status: list[str] | None = Field(
        default=None, description=f"Repeatable. One of: {', '.join(STATUSES)}")
    stage_no: list[int] | None = Field(default=None, description="Repeatable, 1-7.")
    zone_cd: list[ZoneCode] | None = Field(default=None, description="Repeatable.")
    complaint_type_cd: list[Code] | None = Field(default=None, description="Repeatable.")
    source: list[str] | None = Field(default=None, description="Repeatable.")
    assignee_user_id: list[UserId] | None = Field(
        default=None, description="Repeatable. Matches the OPEN survey assignment only.")
    priority: list[str] | None = Field(
        default=None, description=f"Repeatable. One of: {', '.join(PRIORITIES)}")
    ulpin: list[str] | None = Field(default=None, description="Repeatable. Exact match.")
    khasra_no: list[str] | None = Field(default=None, description="Repeatable. Exact match.")
    village_lgd_code: list[str] | None = Field(default=None, description="Repeatable.")
    mine: bool = Field(
        default=False,
        description="Only cases whose open survey assignment is the caller's. "
                    "This is what the field app sends.",
    )
    filed_from: date | None = Field(default=None, description="Inclusive, on the filed date.")
    filed_to: date | None = Field(default=None, description="Inclusive, on the filed date.")

    @model_validator(mode="after")
    def _known_vocabulary(self) -> CaseQuery:
        for value in self.status or ():
            if value not in STATUSES:
                raise ValueError(f"unknown status '{value}'; one of: {', '.join(STATUSES)}")
        for value in self.source or ():
            if value not in SOURCES:
                raise ValueError(f"unknown source '{value}'; one of: {', '.join(SOURCES)}")
        for value in self.priority or ():
            if value not in PRIORITIES:
                raise ValueError(
                    f"unknown priority '{value}'; one of: {', '.join(PRIORITIES)}")
        for value in self.stage_no or ():
            if not 1 <= value <= 7:
                raise ValueError("stage_no is between 1 and 7")
        if self.filed_from and self.filed_to and self.filed_from > self.filed_to:
            raise ValueError("filed_from must not be after filed_to")
        return self


class CaseRow(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    case_ref: str
    zone_cd: str
    zone_name: str
    property_address: str | None = None
    landmark: str | None = None
    complainant_name: str | None = None
    complaint_type_cd: str | None = None
    complaint_type_label: str | None = None
    other_type: str | None = None
    measured_area_sqm: float | None = None
    priority: str | None = None
    ulpin: str | None = None
    khasra_no: str | None = None
    village_lgd_code: str | None = None
    status: str
    stage_no: int
    current_round: int
    source: str
    assignee_user_id: str | None = None
    raised_at: IstDateTime

    @computed_field
    @property
    def parcel_id(self) -> str | None:
        if self.ulpin:
            return self.ulpin
        if self.khasra_no:
            return (f"{self.village_lgd_code}/{self.khasra_no}"
                    if self.village_lgd_code else self.khasra_no)
        return None


class CaseAssignmentOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    assignee_user_id: str
    assigned_by: str
    assignment_type: str
    note: str | None = None
    assigned_at: IstDateTime
    active: bool
    released_at: IstDateTime | None = None


class InspectionRoundOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    inspection_ref: str
    round_no: int
    surveyor_user_id: str
    status: str
    submitted_at: IstDateTime | None = None
    measured_area_sqm: float | None = None


class CaseDetail(CaseRow):
    detail: str | None = None
    complainant_phone: str | None = None
    complainant_email: str | None = None
    owner_name: str | None = None
    owner_phone: str | None = None
    police_station: str | None = None
    pin_code: str | None = None
    district: str | None = None
    state: str | None = None
    country: str | None = None
    property_type_cd: str | None = None
    floor_count: int | None = None
    detection_id: int | None = None
    district_lgd_code: str | None = None
    idempotency_key: str | None = None
    location: dict | None = None
    closed_at: IstDateTime | None = None
    created_by: str | None = None
    updated_at: IstDateTime

    assignment: CaseAssignmentOut | None = None
    rounds: list[InspectionRoundOut] = Field(default_factory=list)
    evidence_count: int = 0
    allowed_actions: list[str] = Field(
        default_factory=list,
        description="What THIS caller may do next, from workflow.allowed_actions. "
                    "A convenience for rendering buttons, never a control: "
                    "workflow.check runs on every request regardless.",
    )
