#!/usr/bin/env bash
# Brings a LIVE realm up to what realm-ada.json declares, plus the few settings
# the import file cannot hold.
#
# --import-realm is IGNORE_EXISTING: once the realm is in Postgres, edits to the
# JSON change nothing. Run this after `make nuke CONFIRM=yes`, after a database
# restore, and after any change to realm-ada.json on an estate that already has
# the realm. Without it the portal cannot sign anybody in and
# /api/icms/admin/users answers 503. See infra/keycloak/README.md.
#
# Only in this script (the JSON cannot express them):
#   - master realm frontendUrl          master is never imported
#   - ada-web origins from APP_ORIGIN   compose does not pass APP_ORIGIN to Keycloak
#   - the ada-api client secret         generated by Keycloak, written to a 0600 file
#
# Also re-asserted here for estates imported before the JSON carried them:
# ada-web direct grants, Conditional OTP, ada-api, ada-field, session lifetimes,
# ada-auth's role scope and its token-exchange permission.
#
# Idempotent. Credentials come from the container's own environment; no secret
# is printed.
set -euo pipefail

CONTAINER="${KC_CONTAINER:-ada-keycloak}"
REALM="${KC_REALM:-pcsmcpl}"
# The host port compose publishes Keycloak on (infra/compose/docker-compose.yml).
ADMIN_PORT="${KC_HTTP_HOST_PORT:-8090}"
ADMIN_URL="${KC_ADMIN_URL:-http://localhost:${ADMIN_PORT}/idp}"
# The portal origin; SPA_ORIGIN is the old name and still honoured.
APP_ORIGIN="${APP_ORIGIN:-${SPA_ORIGIN:-http://localhost:5173}}"
APP_ORIGIN="${APP_ORIGIN%/}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SECRET_FILE="${ADA_API_SECRET_FILE:-${SCRIPT_DIR}/../secrets/keycloak/ada-api-client-secret}"

if ! docker ps --format '{{.Names}}' | grep -qx "$CONTAINER"; then
  echo "Keycloak container '$CONTAINER' is not running. Start it with: make up" >&2
  exit 1
fi

# ada-web: the JSON's loopback entries plus APP_ORIGIN, deduplicated.
WEB_ORIGINS_JSON=$(python3 - "$APP_ORIGIN" <<'PY'
import json, sys
origins = [sys.argv[1], "http://localhost:5173", "http://127.0.0.1:5173",
           "http://localhost:8010", "http://127.0.0.1:8010"]
seen = list(dict.fromkeys(origins))
print(json.dumps(seen))
print(json.dumps([o + "/*" for o in seen]))
PY
)
WEB_ORIGINS=$(printf '%s\n' "$WEB_ORIGINS_JSON" | sed -n 1p)
WEB_REDIRECTS=$(printf '%s\n' "$WEB_ORIGINS_JSON" | sed -n 2p)

docker exec -i "$CONTAINER" sh -s <<EOF
set -eu
K=/opt/keycloak/bin/kcadm.sh
R="$REALM"

\$K config credentials \
  --server "http://localhost:\${KC_HTTP_PORT:-8090}\${KC_HTTP_RELATIVE_PATH:-/idp}" --realm master \
  --user "\$KC_BOOTSTRAP_ADMIN_USERNAME" --password "\$KC_BOOTSTRAP_ADMIN_PASSWORD" >/dev/null

cid() { \$K get clients -r \$R -q clientId=\$1 --fields id --format csv --noquotes | tail -1; }

WEB=\$(cid ada-web)

# The login form posts credentials itself; without this it gets 400 unauthorized_client.
# Keycloak enforces webOrigins on browser token POSTs. Missing origin = 403 Invalid origin.
\$K update clients/\$WEB -r \$R -s directAccessGrantsEnabled=true \
  -s 'webOrigins=${WEB_ORIGINS}' -s 'redirectUris=${WEB_REDIRECTS}'
echo "  ada-web directAccessGrantsEnabled -> true; origins -> ${APP_ORIGIN} and loopback"

# Fails open if left DISABLED: the direct grant would issue tokens on the
# password alone and skip the authenticator silently. Asserted, not assumed.
EXEC=\$(\$K get authentication/flows/direct%20grant/executions -r \$R \
  --fields id,displayName --format csv --noquotes \
  | grep 'Direct Grant - Conditional OTP' | cut -d, -f1)
if [ -n "\$EXEC" ]; then
  \$K update authentication/flows/direct%20grant/executions -r \$R \
    -b "{\"id\":\"\$EXEC\",\"requirement\":\"CONDITIONAL\"}"
  echo "  direct grant 'Conditional OTP' -> CONDITIONAL"
fi

RM=\$(cid realm-management)

# Service account for /api/icms/admin/users. Narrowest roles that work, not realm-admin.
if [ -z "\$(cid ada-api)" ]; then
  \$K create clients -r \$R \
    -s clientId=ada-api -s name='ADA API service' -s enabled=true \
    -s publicClient=false -s serviceAccountsEnabled=true \
    -s standardFlowEnabled=false -s implicitFlowEnabled=false \
    -s directAccessGrantsEnabled=false -s fullScopeAllowed=false \
    -s 'redirectUris=[]' -s 'webOrigins=[]' \
    -s 'defaultClientScopes=["basic","roles"]' -s 'optionalClientScopes=[]' >/dev/null
  echo "  ada-api client created"
fi

CID=\$(cid ada-api)
SA=\$(\$K get clients/\$CID/service-account-user -r \$R --fields id --format csv --noquotes | tail -1)

ROLES=/tmp/ada-api-roles.json
printf '[' > \$ROLES
FIRST=1
for n in view-users query-users manage-users view-realm manage-realm; do
  [ \$FIRST -eq 0 ] && printf ',' >> \$ROLES
  FIRST=0
  \$K get clients/\$RM/roles/\$n -r \$R --fields id,name >> \$ROLES
done
printf ']' >> \$ROLES

# BOTH mappings are required. fullScopeAllowed is false, so a role granted only
# on the service-account user leaves the token with no resource_access entry and
# every Admin API call answers 403.
\$K create users/\$SA/role-mappings/clients/\$RM -r \$R -f \$ROLES >/dev/null 2>&1 || true
\$K create clients/\$CID/scope-mappings/clients/\$RM -r \$R -f \$ROLES >/dev/null 2>&1 || true
rm -f \$ROLES
echo "  ada-api service account + client scope -> view-users query-users manage-users view-realm manage-realm"

# ada-auth: the OTP service refuses to mint a token for any subject holding a
# privileged realm-management client role, and that check reads the
# realm-management client by clientId first, which needs query-clients on the
# service account. Idempotent for realms imported before this role was added.
AUTH_CID=\$(cid ada-auth)
AUTH_SA=\$(\$K get clients/\$AUTH_CID/service-account-user -r \$R --fields id --format csv --noquotes | tail -1)
AUTH_ROLES=/tmp/ada-auth-roles.json
printf '[' > \$AUTH_ROLES
FIRST=1
for n in view-users query-clients impersonation; do
  [ \$FIRST -eq 0 ] && printf ',' >> \$AUTH_ROLES
  FIRST=0
  \$K get clients/\$RM/roles/\$n -r \$R --fields id,name >> \$AUTH_ROLES
done
printf ']' >> \$AUTH_ROLES
\$K create users/\$AUTH_SA/role-mappings/clients/\$RM -r \$R -f \$AUTH_ROLES >/dev/null 2>&1 || true
\$K create clients/\$AUTH_CID/scope-mappings/clients/\$RM -r \$R -f \$AUTH_ROLES >/dev/null 2>&1 || true
rm -f \$AUTH_ROLES
echo "  ada-auth service account + client scope -> view-users query-clients impersonation"

# ada-field: the native field app. Today it signs in with a direct access grant
# from its own form; the standard flow is on, PKCE S256 only, for the planned
# system-browser login (redirect adaicms://...).
if [ -z "\$(cid ada-field)" ]; then
  \$K create clients -r \$R -s clientId=ada-field -s enabled=true >/dev/null
  echo "  ada-field client created"
fi
FID=\$(cid ada-field)
\$K update clients/\$FID -r \$R \
  -s name='ADA ICMS Field App' -s publicClient=true \
  -s standardFlowEnabled=true -s implicitFlowEnabled=false \
  -s directAccessGrantsEnabled=true -s serviceAccountsEnabled=false \
  -s fullScopeAllowed=true -s 'redirectUris=["adaicms://*"]' -s 'webOrigins=["+"]' \
  -s 'attributes."post.logout.redirect.uris"=adaicms://*' \
  -s 'attributes."pkce.code.challenge.method"=S256' \
  -s 'attributes."backchannel.logout.revoke.offline.tokens"=true'
OFF=\$(\$K get client-scopes -r \$R --fields id,name --format csv --noquotes | grep ',offline_access\$' | cut -d, -f1)
\$K update clients/\$FID/optional-client-scopes/\$OFF -r \$R 2>/dev/null || true
for S in \$(\$K get clients/\$FID/optional-client-scopes -r \$R --fields id,name --format csv --noquotes \
    | grep -v ',offline_access\$' | cut -d, -f1); do
  \$K delete clients/\$FID/optional-client-scopes/\$S -r \$R
done
if ! \$K get clients/\$FID/protocol-mappers/models -r \$R --fields name --format csv --noquotes | grep -qx phoneNumber; then
  \$K create clients/\$FID/protocol-mappers/models -r \$R \
    -s name=phoneNumber -s protocol=openid-connect -s protocolMapper=oidc-usermodel-attribute-mapper \
    -s 'config."user.attribute"=phoneNumber' -s 'config."claim.name"=phoneNumber' \
    -s 'config."jsonType.label"=String' -s 'config."id.token.claim"=true' \
    -s 'config."access.token.claim"=false' -s 'config."userinfo.token.claim"=true' \
    -s 'config."introspection.token.claim"=true' >/dev/null
fi
echo "  ada-field -> public, direct grant + PKCE S256 standard flow, offline_access optional"

# Lifetimes (S-08). Same values as realm-ada.json; the reasons are in README.md.
\$K update realms/\$R \
  -s accessTokenLifespan=900 \
  -s ssoSessionIdleTimeout=3600 -s ssoSessionMaxLifespan=43200 \
  -s offlineSessionIdleTimeout=2592000 \
  -s offlineSessionMaxLifespanEnabled=true -s offlineSessionMaxLifespan=7776000 \
  -s revokeRefreshToken=true -s refreshTokenMaxReuse=0
echo "  lifetimes -> access 15m, SSO 1h idle / 12h max, offline 30d idle / 90d max"

# ada-auth mints OTP sign-in tokens by exchange and has fullScopeAllowed=false,
# so these realm roles must be in its scope or the token has no realm_access.
# super-admin is left out on purpose.
AUTH=\$(cid ada-auth)
for n in pcs-nodal-officer field-surveyor ada-project-lead; do
  if \$K get roles/\$n -r \$R >/dev/null 2>&1; then
    ROLE=\$(\$K get roles/\$n -r \$R --fields id,name)
    \$K create clients/\$AUTH/scope-mappings/realm -r \$R -b "[\$ROLE]" >/dev/null 2>&1 || true
  fi
done
echo "  ada-auth realm scope -> pcs-nodal-officer field-surveyor ada-project-lead"

# ada-auth may exchange to audience ada-web. This is a fine-grained admin
# permission (v1) and exists only when Keycloak runs with admin-fine-grained-authz:v1.
if \$K get clients/\$WEB/management/permissions -r \$R >/dev/null 2>&1; then
  \$K update clients/\$WEB/management/permissions -r \$R -s enabled=true >/dev/null
  POL=\$(\$K get clients/\$RM/authz/resource-server/policy -r \$R -q 'name=ada-auth may exchange' \
    --fields id,name --format csv --noquotes | grep ',ada-auth may exchange\$' | cut -d, -f1)
  if [ -z "\$POL" ]; then
    \$K create clients/\$RM/authz/resource-server/policy/client -r \$R \
      -s 'name=ada-auth may exchange' -s logic=POSITIVE -s decisionStrategy=UNANIMOUS \
      -s "clients=[\"\$AUTH\"]" >/dev/null
    POL=\$(\$K get clients/\$RM/authz/resource-server/policy -r \$R -q 'name=ada-auth may exchange' \
      --fields id,name --format csv --noquotes | grep ',ada-auth may exchange\$' | cut -d, -f1)
  fi
  PERM=\$(\$K get clients/\$RM/authz/resource-server/permission -r \$R \
    -q "name=token-exchange.permission.client.\$WEB" --fields id --format csv --noquotes | tail -1)
  \$K update clients/\$RM/authz/resource-server/permission/scope/\$PERM -r \$R -s "policies=[\"\$POL\"]"
  echo "  ada-web token-exchange permission -> ada-auth"
else
  echo "  SKIPPED ada-web token-exchange permission: Keycloak lacks --features=admin-fine-grained-authz:v1."
  echo "          auth-otp's exchange with audience=ada-web will answer 403 until it has it,"
  echo "          or until auth-otp runs with EXCHANGE_AUDIENCE= (empty). See README.md."
fi

# KC_HOSTNAME points every realm at the SPA origin. For master that leaves the
# admin console unreachable whenever the frontend is down, and its session-check
# iframe times out. A realm-level frontendUrl overrides it for master alone.
# Last on purpose: it changes master's issuer, which voids this session's token.
\$K update realms/master -s "attributes.frontendUrl=${ADMIN_URL}"
echo "  master frontendUrl -> ${ADMIN_URL}"
EOF

# The ada-api secret goes to a 0600 file, never to the terminal.
mkdir -p "$(dirname "$SECRET_FILE")"
( umask 077
  docker exec -i "$CONTAINER" sh -s > "$SECRET_FILE" <<EOF
set -eu
K=/opt/keycloak/bin/kcadm.sh
\$K config credentials \
  --server "http://localhost:\${KC_HTTP_PORT:-8090}\${KC_HTTP_RELATIVE_PATH:-/idp}" --realm master \
  --user "\$KC_BOOTSTRAP_ADMIN_USERNAME" --password "\$KC_BOOTSTRAP_ADMIN_PASSWORD" >/dev/null
CID=\$(\$K get clients -r "$REALM" -q clientId=ada-api --fields id --format csv --noquotes | tail -1)
\$K get clients/\$CID/client-secret -r "$REALM" --fields value --format csv --noquotes | tail -1
EOF
)
chmod 600 "$SECRET_FILE"
SUFFIX=$(tr -d '\n' < "$SECRET_FILE" | tail -c 4)
echo
echo "ada-api client secret (...${SUFFIX}) written to ${SECRET_FILE} (mode 0600)."
echo "Put it in infra/compose/.env as ADA_API_CLIENT_SECRET, then delete the file."

cat <<MSG

Verify direct grants are on — expect invalid_grant, NOT unauthorized_client:

  curl -sS -X POST http://localhost:${ADMIN_PORT}/idp/realms/${REALM}/protocol/openid-connect/token \\
    -H 'Origin: ${APP_ORIGIN}' \\
    -d grant_type=password -d client_id=ada-web -d username=__probe__ -d password=__probe__

Same check for the field app (no Origin header — it is not a browser):

  curl -sS -X POST http://localhost:${ADMIN_PORT}/idp/realms/${REALM}/protocol/openid-connect/token \\
    -d grant_type=password -d client_id=ada-field -d username=__probe__ -d password=__probe__

Admin console: ${ADMIN_URL}/admin
MSG
