"""baseline — the platform and ICMS schema as of 18 September 2026

Everything that existed before Alembic: the five platform tables, which had been
created by `Base.metadata.create_all`, and the seventeen ICMS tables, which had
been raw DDL. From here the schema changes only through a revision.

The table definitions are autogenerated. What is hand-added is the part
autogenerate cannot see:

  * The PostGIS extension, FIRST, because the geometry columns below reference
    a type it defines.
  * Two PL/pgSQL functions and the five triggers that use them — updated_at
    maintenance, and the append-only guards on evidence and the audit trail.
  * The seed vocabulary, without which a case cannot be created at all.

An existing deployment already has the five platform tables. It is stamped at
this revision rather than upgraded to it — see ada_core.migrate.run_migrations.

Revision ID: 0001
Revises: 
Create Date: 2026-09-18 08:01:07.799936+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from ada_core.types import Geometry

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


FUNCTIONS = """
CREATE OR REPLACE FUNCTION icms_touch_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- A trigger that raises rather than a rule that silently discards: a caller
-- trying to delete evidence has a bug and must be told so.
CREATE OR REPLACE FUNCTION icms_refuse_delete() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'icms: % is append-only; row % cannot be deleted',
        TG_TABLE_NAME, OLD.id;
END;
$$ LANGUAGE plpgsql;
"""

TRIGGERS = [
    ("trg_icms_case_touch", "icms_case", "BEFORE UPDATE", "icms_touch_updated_at"),
    ("trg_icms_inspection_touch", "icms_inspection", "BEFORE UPDATE",
     "icms_touch_updated_at"),
    ("trg_icms_notice_touch", "icms_notice", "BEFORE UPDATE", "icms_touch_updated_at"),
    # The case may be litigated. A delete path that exists is a delete path that
    # is eventually called.
    ("trg_icms_evidence_no_delete", "icms_evidence", "BEFORE DELETE",
     "icms_refuse_delete"),
    ("trg_icms_case_event_no_delete", "icms_case_event", "BEFORE DELETE",
     "icms_refuse_delete"),
]

# Provisional. Replaced by the real values once the legacy pcs_code_value table
# is read — docs/icms/schema/legacy-inventory.md, open question O5.
SEED = [
    ("complaint_type", "unauthorised_construction", "Unauthorised construction", 1),
    ("complaint_type", "deviation_from_plan", "Deviation from sanctioned plan", 2),
    ("complaint_type", "encroachment", "Encroachment on public land", 3),
    ("complaint_type", "illegal_colony", "Illegal colony development", 4),
    ("complaint_type", "other", "Other", 99),
    ("property_type", "residential", "Residential", 1),
    ("property_type", "commercial", "Commercial", 2),
    ("property_type", "industrial", "Industrial", 3),
    ("property_type", "institutional", "Institutional", 4),
    ("property_type", "vacant_land", "Vacant land", 5),
    ("area_type", "built_up", "Built up", 1),
    ("area_type", "under_construction", "Under construction", 2),
    ("area_type", "vacant", "Vacant", 3),
    ("delivery_mode", "hand", "By hand", 1),
    ("delivery_mode", "registered_post", "Registered post", 2),
    ("delivery_mode", "affixation", "Affixation at site", 3),
    ("delivery_mode", "email", "Email", 4),
]


def upgrade() -> None:
    # PostGIS first: every geometry column below references a type it defines,
    # so a create_table without it fails on 'type "geometry" does not exist'.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icms_campus_boundary',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('geom', Geometry('MultiPolygon', srid=4326), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_icms_campus_geom', 'icms_campus_boundary', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('icms_code_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('label_hi', sa.Text(), nullable=True),
    sa.Column('parent_code', sa.String(length=40), nullable=True),
    sa.Column('sort_order', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain', 'code', name='icms_code_value_uq')
    )
    op.create_table('icms_notice_sequence',
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('last_seq', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('icms_zone',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('zone_cd', sa.String(length=40), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_hi', sa.Text(), nullable=True),
    sa.Column('parent_cd', sa.String(length=40), nullable=True),
    sa.Column('geom', Geometry('MultiPolygon', srid=4326), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_cd')
    )
    op.create_index('ix_icms_zone_geom', 'icms_zone', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_icms_zone_parent', 'icms_zone', ['parent_cd'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('icms_zone_assignment',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('zone_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('assigned_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['icms_zone.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_icms_zone_assignment_user', 'icms_zone_assignment', ['user_id'], unique=False)
    op.create_index('uq_icms_zone_assignment_active', 'icms_zone_assignment', ['zone_id', 'user_id'], unique=True, postgresql_where=sa.text('active'), sqlite_where=sa.text('active'))
    op.create_table('rasters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('original_path', sa.Text(), nullable=False),
    sa.Column('cog_path', sa.Text(), nullable=True),
    sa.Column('crs', sa.String(length=100), nullable=True),
    sa.Column('bounds_4326', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('resolution_m', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(length=120), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rasters_project_id'), 'rasters', ['project_id'], unique=False)
    op.create_table('red_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('geometry', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_red_zones_project_id'), 'red_zones', ['project_id'], unique=False)
    op.create_table('analysis_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('raster_t1_id', sa.Integer(), nullable=False),
    sa.Column('raster_t2_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(length=200), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('mask_cog_path', sa.Text(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raster_t1_id'], ['rasters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raster_t2_id'], ['rasters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_project_id'), 'analysis_jobs', ['project_id'], unique=False)
    op.create_table('change_polygons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('geometry', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('review_status', sa.String(length=12), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=64), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_polygons_job_id'), 'change_polygons', ['job_id'], unique=False)
    op.create_index(op.f('ix_change_polygons_review_status'), 'change_polygons', ['review_status'], unique=False)
    op.create_table('icms_case',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('case_ref', sa.String(length=16), nullable=False),
    sa.Column('zone_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('detection_id', sa.Integer(), nullable=True),
    sa.Column('complaint_type_cd', sa.String(length=40), nullable=True),
    sa.Column('other_type', sa.Text(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('complainant_name', sa.Text(), nullable=True),
    sa.Column('complainant_phone', sa.String(length=20), nullable=True),
    sa.Column('complainant_email', sa.Text(), nullable=True),
    sa.Column('owner_name', sa.Text(), nullable=True),
    sa.Column('owner_phone', sa.String(length=20), nullable=True),
    sa.Column('property_address', sa.Text(), nullable=True),
    sa.Column('landmark', sa.Text(), nullable=True),
    sa.Column('police_station', sa.Text(), nullable=True),
    sa.Column('pin_code', sa.String(length=10), nullable=True),
    sa.Column('district', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), server_default=sa.text("'India'"), nullable=True),
    sa.Column('property_type_cd', sa.String(length=40), nullable=True),
    sa.Column('floor_count', sa.SmallInteger(), nullable=True),
    sa.Column('location', Geometry('Point', srid=4326), nullable=True),
    sa.Column('stage_no', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'raised'"), nullable=False),
    sa.Column('current_round', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('raised_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('detection', 'public', 'field', 'office')", name='icms_case_source_ck'),
    sa.CheckConstraint("status IN ('raised', 'assigned', 'under_inspection', 'inspection_submitted', 'resurvey_requested', 'verified', 'handed_over', 'confirmed', 'notice_issued', 'closed', 'rejected')", name='icms_case_status_ck'),
    sa.CheckConstraint('stage_no BETWEEN 1 AND 7', name='icms_case_stage_ck'),
    sa.ForeignKeyConstraint(['detection_id'], ['change_polygons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['icms_zone.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_ref')
    )
    op.create_index('ix_icms_case_detect', 'icms_case', ['detection_id'], unique=False)
    op.create_index('ix_icms_case_geom', 'icms_case', ['location'], unique=False, postgresql_using='gist')
    op.create_index('ix_icms_case_raised', 'icms_case', ['raised_at'], unique=False)
    op.create_index('ix_icms_case_stage', 'icms_case', ['stage_no'], unique=False)
    op.create_index('ix_icms_case_status', 'icms_case', ['status'], unique=False)
    op.create_index('ix_icms_case_zone', 'icms_case', ['zone_id'], unique=False)
    op.create_table('icms_case_assignment',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('assignee_user_id', sa.String(length=64), nullable=False),
    sa.Column('assigned_by', sa.String(length=64), nullable=False),
    sa.Column('assignment_type', sa.String(length=20), server_default=sa.text("'survey'"), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("assignment_type IN ('survey', 'verification', 'handover')", name='icms_case_assignment_type_ck'),
    sa.ForeignKeyConstraint(['case_id'], ['icms_case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_icms_case_assignment_case', 'icms_case_assignment', ['case_id'], unique=False)
    op.create_index('ix_icms_case_assignment_user', 'icms_case_assignment', ['assignee_user_id'], unique=False, postgresql_where=sa.text('active'), sqlite_where=sa.text('active'))
    op.create_index('uq_icms_case_assignment_open', 'icms_case_assignment', ['case_id', 'assignment_type'], unique=True, postgresql_where=sa.text('active'), sqlite_where=sa.text('active'))
    op.create_table('icms_feedback',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', Geometry('Point', srid=4326), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['icms_case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_icms_feedback_case', 'icms_feedback', ['case_id'], unique=False)
    op.create_table('icms_inspection',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('inspection_ref', sa.String(length=16), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('round_no', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('surveyor_user_id', sa.String(length=64), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'scheduled'"), nullable=False),
    sa.Column('occupant_name', sa.Text(), nullable=True),
    sa.Column('occupant_phone', sa.String(length=20), nullable=True),
    sa.Column('area_type_cd', sa.String(length=40), nullable=True),
    sa.Column('measured_area_sqm', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notice_required', sa.Boolean(), nullable=True),
    sa.Column('notice_act_cd', sa.String(length=40), nullable=True),
    sa.Column('officer_note', sa.Text(), nullable=True),
    sa.Column('location', Geometry('Point', srid=4326), nullable=True),
    sa.Column('location_accuracy_m', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'in_progress', 'submitted', 'accepted', 'rejected')", name='icms_inspection_status_ck'),
    sa.CheckConstraint('round_no >= 1', name='icms_inspection_round_ck'),
    sa.ForeignKeyConstraint(['case_id'], ['icms_case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'round_no', name='icms_inspection_round_uq'),
    sa.UniqueConstraint('inspection_ref')
    )
    op.create_index('ix_icms_inspection_case', 'icms_inspection', ['case_id'], unique=False)
    op.create_index('ix_icms_inspection_geom', 'icms_inspection', ['location'], unique=False, postgresql_using='gist')
    op.create_index('ix_icms_inspection_status', 'icms_inspection', ['status'], unique=False)
    op.create_index('ix_icms_inspection_surveyor', 'icms_inspection', ['surveyor_user_id'], unique=False)
    op.create_table('icms_resurvey_request',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('from_round', sa.SmallInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decision', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('resulting_round', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint("decision IN ('pending', 'approved', 'rejected')", name='icms_resurvey_decision_ck'),
    sa.ForeignKeyConstraint(['case_id'], ['icms_case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_icms_resurvey_case', 'icms_resurvey_request', ['case_id'], unique=False)
    op.create_index('uq_icms_resurvey_pending', 'icms_resurvey_request', ['case_id'], unique=True, postgresql_where=sa.text("decision = 'pending'"), sqlite_where=sa.text("decision = 'pending'"))
    op.create_table('icms_case_event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('inspection_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=True),
    sa.Column('round_no', sa.SmallInteger(), nullable=True),
    sa.Column('actor_user_id', sa.String(length=64), nullable=False),
    sa.Column('actor_role', sa.String(length=60), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['icms_case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspection_id'], ['icms_inspection.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_icms_case_event_case', 'icms_case_event', ['case_id', 'created_at'], unique=False)
    op.create_table('icms_check_in',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('inspection_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('location', Geometry('Point', srid=4326), nullable=False),
    sa.Column('accuracy_m', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('device_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('server_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('capture_source', sa.String(length=20), server_default=sa.text("'gps'"), nullable=False),
    sa.Column('inside_zone', sa.Boolean(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=36), nullable=False),
    sa.CheckConstraint("capture_source IN ('gps', 'network', 'fused', 'manual')", name='icms_check_in_source_ck'),
    sa.ForeignKeyConstraint(['inspection_id'], ['icms_inspection.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_icms_check_in_geom', 'icms_check_in', ['location'], unique=False, postgresql_using='gist')
    op.create_index('ix_icms_check_in_inspection', 'icms_check_in', ['inspection_id'], unique=False)
    op.create_table('icms_evidence',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('inspection_id', sa.BigInteger(), nullable=True),
    sa.Column('round_no', sa.SmallInteger(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('doc_type_cd', sa.String(length=40), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('byte_size', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('location', Geometry('Point', srid=4326), nullable=True),
    sa.Column('accuracy_m', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('device_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capture_source', sa.String(length=20), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_by', sa.String(length=64), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=36), nullable=False),
    sa.CheckConstraint("capture_source IN ('camera', 'gallery', 'upload', 'system') OR capture_source IS NULL", name='icms_evidence_source_ck'),
    sa.CheckConstraint("kind <> 'photo' OR (location IS NOT NULL AND accuracy_m IS NOT NULL AND device_timestamp IS NOT NULL AND capture_source IS NOT NULL)", name='icms_evidence_geotag_ck'),
    sa.CheckConstraint("kind IN ('photo', 'video', 'document', 'signature')", name='icms_evidence_kind_ck'),
    sa.ForeignKeyConstraint(['case_id'], ['icms_case.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspection_id'], ['icms_inspection.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_icms_evidence_case', 'icms_evidence', ['case_id'], unique=False)
    op.create_index('ix_icms_evidence_geom', 'icms_evidence', ['location'], unique=False, postgresql_using='gist')
    op.create_index('ix_icms_evidence_inspection', 'icms_evidence', ['inspection_id'], unique=False)
    op.create_table('icms_inspection_finding',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('inspection_id', sa.BigInteger(), nullable=False),
    sa.Column('seq', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('finding', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['icms_inspection.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inspection_id', 'seq', name='icms_inspection_finding_uq')
    )
    op.create_table('icms_inspection_section',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('inspection_id', sa.BigInteger(), nullable=False),
    sa.Column('act_cd', sa.String(length=40), nullable=False),
    sa.Column('section_cd', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['icms_inspection.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inspection_id', 'act_cd', 'section_cd', name='icms_inspection_section_uq')
    )
    op.create_table('icms_notice',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('notice_ref', sa.String(length=16), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('inspection_id', sa.BigInteger(), nullable=True),
    sa.Column('act_cd', sa.String(length=40), nullable=False),
    sa.Column('section_cds', postgresql.ARRAY(sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('issuing_authority', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('issued_by', sa.String(length=64), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('compliance_due', sa.Date(), nullable=True),
    sa.Column('artefact_path', sa.Text(), nullable=True),
    sa.Column('artefact_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'issued', 'delivered', 'failed', 'withdrawn')", name='icms_notice_status_ck'),
    sa.ForeignKeyConstraint(['case_id'], ['icms_case.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspection_id'], ['icms_inspection.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notice_ref')
    )
    op.create_index('ix_icms_notice_case', 'icms_notice', ['case_id'], unique=False)
    op.create_index('ix_icms_notice_status', 'icms_notice', ['status'], unique=False)
    op.create_table('icms_notice_delivery',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('notice_id', sa.BigInteger(), nullable=False),
    sa.Column('mode_cd', sa.String(length=40), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recipient_name', sa.Text(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('location', Geometry('Point', srid=4326), nullable=True),
    sa.Column('accuracy_m', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('officer_note', sa.Text(), nullable=True),
    sa.Column('evidence_id', sa.BigInteger(), nullable=True),
    sa.Column('recorded_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['icms_evidence.id'], ),
    sa.ForeignKeyConstraint(['notice_id'], ['icms_notice.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_icms_notice_delivery_notice', 'icms_notice_delivery', ['notice_id'], unique=False)
    # ### end Alembic commands ###

    op.execute(FUNCTIONS)
    for name, table, timing, function in TRIGGERS:
        op.execute(f"DROP TRIGGER IF EXISTS {name} ON {table}")
        op.execute(
            f"CREATE TRIGGER {name} {timing} ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION {function}()")

    op.bulk_insert(
        sa.table(
            "icms_code_value",
            sa.column("domain", sa.String),
            sa.column("code", sa.String),
            sa.column("label", sa.Text),
            sa.column("sort_order", sa.SmallInteger),
        ),
        [{"domain": d, "code": c, "label": lbl, "sort_order": o}
         for d, c, lbl, o in SEED],
    )


def downgrade() -> None:
    for name, table, _timing, _function in TRIGGERS:
        op.execute(f"DROP TRIGGER IF EXISTS {name} ON {table}")
    op.execute("DROP FUNCTION IF EXISTS icms_touch_updated_at()")
    op.execute("DROP FUNCTION IF EXISTS icms_refuse_delete()")
    # The extension is NOT dropped. Another schema in the same database may be
    # using it, and dropping it would take their geometry columns with it.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_icms_notice_delivery_notice', table_name='icms_notice_delivery')
    op.drop_table('icms_notice_delivery')
    op.drop_index('ix_icms_notice_status', table_name='icms_notice')
    op.drop_index('ix_icms_notice_case', table_name='icms_notice')
    op.drop_table('icms_notice')
    op.drop_table('icms_inspection_section')
    op.drop_table('icms_inspection_finding')
    op.drop_index('ix_icms_evidence_inspection', table_name='icms_evidence')
    op.drop_index('ix_icms_evidence_geom', table_name='icms_evidence', postgresql_using='gist')
    op.drop_index('ix_icms_evidence_case', table_name='icms_evidence')
    op.drop_table('icms_evidence')
    op.drop_index('ix_icms_check_in_inspection', table_name='icms_check_in')
    op.drop_index('ix_icms_check_in_geom', table_name='icms_check_in', postgresql_using='gist')
    op.drop_table('icms_check_in')
    op.drop_index('ix_icms_case_event_case', table_name='icms_case_event')
    op.drop_table('icms_case_event')
    op.drop_index('uq_icms_resurvey_pending', table_name='icms_resurvey_request', postgresql_where=sa.text("decision = 'pending'"), sqlite_where=sa.text("decision = 'pending'"))
    op.drop_index('ix_icms_resurvey_case', table_name='icms_resurvey_request')
    op.drop_table('icms_resurvey_request')
    op.drop_index('ix_icms_inspection_surveyor', table_name='icms_inspection')
    op.drop_index('ix_icms_inspection_status', table_name='icms_inspection')
    op.drop_index('ix_icms_inspection_geom', table_name='icms_inspection', postgresql_using='gist')
    op.drop_index('ix_icms_inspection_case', table_name='icms_inspection')
    op.drop_table('icms_inspection')
    op.drop_index('ix_icms_feedback_case', table_name='icms_feedback')
    op.drop_table('icms_feedback')
    op.drop_index('uq_icms_case_assignment_open', table_name='icms_case_assignment', postgresql_where=sa.text('active'), sqlite_where=sa.text('active'))
    op.drop_index('ix_icms_case_assignment_user', table_name='icms_case_assignment', postgresql_where=sa.text('active'), sqlite_where=sa.text('active'))
    op.drop_index('ix_icms_case_assignment_case', table_name='icms_case_assignment')
    op.drop_table('icms_case_assignment')
    op.drop_index('ix_icms_case_zone', table_name='icms_case')
    op.drop_index('ix_icms_case_status', table_name='icms_case')
    op.drop_index('ix_icms_case_stage', table_name='icms_case')
    op.drop_index('ix_icms_case_raised', table_name='icms_case')
    op.drop_index('ix_icms_case_geom', table_name='icms_case', postgresql_using='gist')
    op.drop_index('ix_icms_case_detect', table_name='icms_case')
    op.drop_table('icms_case')
    op.drop_index(op.f('ix_change_polygons_review_status'), table_name='change_polygons')
    op.drop_index(op.f('ix_change_polygons_job_id'), table_name='change_polygons')
    op.drop_table('change_polygons')
    op.drop_index(op.f('ix_analysis_jobs_project_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_red_zones_project_id'), table_name='red_zones')
    op.drop_table('red_zones')
    op.drop_index(op.f('ix_rasters_project_id'), table_name='rasters')
    op.drop_table('rasters')
    op.drop_index('uq_icms_zone_assignment_active', table_name='icms_zone_assignment', postgresql_where=sa.text('active'), sqlite_where=sa.text('active'))
    op.drop_index('ix_icms_zone_assignment_user', table_name='icms_zone_assignment')
    op.drop_table('icms_zone_assignment')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_icms_zone_parent', table_name='icms_zone')
    op.drop_index('ix_icms_zone_geom', table_name='icms_zone', postgresql_using='gist')
    op.drop_table('icms_zone')
    op.drop_table('icms_notice_sequence')
    op.drop_table('icms_code_value')
    op.drop_index('ix_icms_campus_geom', table_name='icms_campus_boundary', postgresql_using='gist')
    op.drop_table('icms_campus_boundary')
    # ### end Alembic commands ###
